services:
  app:
    build:
      context: .
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Popillol123.
      POSTGRES_DB: ridesharing

  postgres:
    image: postgis/postgis:15-3.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Popillol123.
      POSTGRES_DB: ridesharing
    ports:
      - "5432:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5